/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    reviews: Review;
    certificates: Certificate;
    faq: Faq;
    steps: Step;
    pricing: Pricing;
    advantages: Advantage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    steps: StepsSelect<false> | StepsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    advantages: AdvantagesSelect<false> | AdvantagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'ru' | 'ru'[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username?: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  category?: ('lawyer' | 'certificates' | 'icons' | 'background' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  /**
   * Название иконки из Material Symbols, например: gavel, home_work, family_restroom
   */
  icon: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  text: string;
  source: 'yandex-karty' | 'yandex-uslugi' | 'harant' | 'avito';
  rating?: number | null;
  /**
   * Формат: дд.мм.гггг
   */
  date?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  title: string;
  image: number | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  page: 'main' | 'male' | 'female';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steps".
 */
export interface Step {
  id: number;
  /**
   * Например: 1, 2, 3...
   */
  number: string;
  title: string;
  description: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  title: string;
  /**
   * Например: от 3 000 ₽, 15 000 ₽, Бесплатно
   */
  price: string;
  description?: string | null;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  popular?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advantages".
 */
export interface Advantage {
  id: number;
  title: string;
  /**
   * Можно использовать <strong>, <br /> для форматирования
   */
  description: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'steps';
        value: number | Step;
      } | null)
    | ({
        relationTo: 'pricing';
        value: number | Pricing;
      } | null)
    | ({
        relationTo: 'advantages';
        value: number | Advantage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  text?: T;
  source?: T;
  rating?: T;
  date?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  page?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steps_select".
 */
export interface StepsSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  title?: T;
  price?: T;
  description?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  popular?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advantages_select".
 */
export interface AdvantagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contacts?: {
    phone1?: string | null;
    phone2?: string | null;
    email?: string | null;
    address?: string | null;
    telegram?: string | null;
    maxLink?: string | null;
    mapEmbed?: string | null;
  };
  hero?: {
    name1?: string | null;
    name2?: string | null;
    sideText1?: string | null;
    sideText2?: string | null;
    sideText3?: string | null;
    ctaButton?: string | null;
    heroImage?: (number | null) | Media;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  about?: {
    subtitle?: string | null;
    title?: string | null;
    titleAccent?: string | null;
    text1?: string | null;
    text2?: string | null;
    text3?: string | null;
    regNumber?: string | null;
    photo?: (number | null) | Media;
  };
  cta?: {
    oldPrice?: string | null;
    newPrice?: string | null;
    priceNote?: string | null;
    title?: string | null;
    points?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaPhoto?: (number | null) | Media;
  };
  malePage?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    heroImage?: (number | null) | Media;
    quoteTitle?: string | null;
    quoteText1?: string | null;
    quoteText2?: string | null;
    quotePhoto?: (number | null) | Media;
    ctaTitle?: string | null;
    painPoints?:
      | {
          icon: string;
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    whatIDo?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  femalePage?: {
    heroTitle?: string | null;
    heroSubtitle?: string | null;
    heroImage?: (number | null) | Media;
    quoteTitle?: string | null;
    quoteText1?: string | null;
    quoteText2?: string | null;
    quotePhoto?: (number | null) | Media;
    ctaTitle?: string | null;
    painPoints?:
      | {
          icon: string;
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    whatIDo?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    mainTitle?: string | null;
    mainDescription?: string | null;
    maleTitle?: string | null;
    maleDescription?: string | null;
    femaleTitle?: string | null;
    femaleDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contacts?:
    | T
    | {
        phone1?: T;
        phone2?: T;
        email?: T;
        address?: T;
        telegram?: T;
        maxLink?: T;
        mapEmbed?: T;
      };
  hero?:
    | T
    | {
        name1?: T;
        name2?: T;
        sideText1?: T;
        sideText2?: T;
        sideText3?: T;
        ctaButton?: T;
        heroImage?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  about?:
    | T
    | {
        subtitle?: T;
        title?: T;
        titleAccent?: T;
        text1?: T;
        text2?: T;
        text3?: T;
        regNumber?: T;
        photo?: T;
      };
  cta?:
    | T
    | {
        oldPrice?: T;
        newPrice?: T;
        priceNote?: T;
        title?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaPhoto?: T;
      };
  malePage?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        heroImage?: T;
        quoteTitle?: T;
        quoteText1?: T;
        quoteText2?: T;
        quotePhoto?: T;
        ctaTitle?: T;
        painPoints?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
        whatIDo?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  femalePage?:
    | T
    | {
        heroTitle?: T;
        heroSubtitle?: T;
        heroImage?: T;
        quoteTitle?: T;
        quoteText1?: T;
        quoteText2?: T;
        quotePhoto?: T;
        ctaTitle?: T;
        painPoints?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
        whatIDo?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        mainTitle?: T;
        mainDescription?: T;
        maleTitle?: T;
        maleDescription?: T;
        femaleTitle?: T;
        femaleDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}